# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://zatoima.github.io/"

# The name of this wonderful theme ;-).
theme = 'hugo-bearblog'

# Basic metadata configuration for your blog.
title = "my opinion is my own"
author = "zatoima"
copyright = "Copyright © 2019, zatoima."

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Enable CJK word counting for accurate reading time
hasCJKLanguage = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
ignoreErrors = ["error-disable-taxonomy"]

[mediaTypes]
  [mediaTypes."text/llms"]
    suffixes = ["txt"]
  [mediaTypes."text/llms-full"]
    suffixes = ["txt"]

[outputFormats]
  [outputFormats.llms]
    mediaType = "text/llms"
    baseName = "llms"
    isPlainText = true
    notAlternative = true
  [outputFormats.llms-full]
    mediaType = "text/llms-full"
    baseName = "llms-full"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "JSON", "llms", "llms-full"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

# for ga4
googleAnalytics = "G-STFZ9QMXGM"

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "memo blog. Hugo on GitHub Pages"

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  favicon = "favicon.svg"

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  images = ["images/share.png"]

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "my opinion is my own"

  # This theme will, by default, inject a made-with-line at the bottom of the page.
  # You can turn it off, but we would really appreciate if you don’t :-).
  # hideMadeWithLine = true

  # By default, this theme displays dates with a format like "02 Jan, 2006", but
  # you can customize it by setting the `dateFormat` param in your site's config
  # file. See [Hugo's Format function docs](https://gohugo.io/functions/format/)
  # for details. An example TOML config that uses [ISO
  # 8601](https://en.wikipedia.org/wiki/ISO_8601) format:
  # dateFormat = "2006-01-02"

  dateFormat="2006-01-02"

  # トップページへの表示件数
  # layouts/partials/list.html にて参照
  latestPostNum=20

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
  [markup.highlight]
    style = "dracula"
    lineNos = false
    noClasses = true
    guessSyntax = true
    tabWidth = 4

[security]
  [security.http]
    methods = ['(?i)GET']
    urls = ['.*']
